services:
  database:
    image: postgres
    restart: always
    environment:
     POSTGRES_USERNAME: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: postgres
    ports:
      - "5432:5432"
volumes:
  data: