server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/ludotheque"
          jwk-set-uri: "http://localhost:8080/realms/ludotheque/protocol/openid-connect/certs"
  application:
    name: ludotheque
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false


  mvc:
    converters:
      preferred-json-mapper: gson
  gson:
    enable-complex-map-key-serialization: true
    serialize-nulls: true
  sql:
    init:
      mode: always
      continue-on-error: true
logging:
  level:
    root: info