POST http://localhost:8081/game/test
Accept: application/x-protobuf
Content-Type: application/x-protobuf
Authorization: Bearer {{$auth.token("spring-resource-oauth")}}

###

GET http://localhost:8081/game/
Accept: application/x-protobuf
Content-Type: application/x-protobuf
Authorization: Bearer {{$auth.token("spring-resource-oauth")}}

###

GET http://localhost:8081/game?page=2&pageSize=40
Accept: application/x-protobuf
Content-Type: application/x-protobuf
Authorization: Bearer {{$auth.token("spring-resource-oauth")}}

###

GET http://localhost:8081/game?page=2&pageSize=40
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("spring-resource-oauth")}}

###

GET http://localhost:8081/game/72ba166b-8c5b-4762-8e7f-6f1a261e3996
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("spring-resource-oauth")}}

###

PUT http://localhost:8081/game/72ba166b-8c5b-4762-8e7f-6f1a261e3996
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("spring-resource-oauth")}}

{
"game":{"images": [
  {"path": "/img/icons/icon-board.svg", "alt": "", "order": 1}
]}
}

###

DELETE http://localhost:8081/game/71b6f540-a59b-4bc7-8f62-9a27aff568e4
Accept: application/x-protobuf
Content-Type: application/json
Authorization: Bearer {{$auth.token("spring-resource-oauth")}}